apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-secret
  namespace: rustfs
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: rustfs-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "rustfs" 
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "a7505f67-ace7-4923-9c36-b3f2010b83eb"
