config:
  cluster:
    enabled: true
    replicas: 3
  jetstream:
    enabled: true
    memoryStore:
      enabled: true
      maxSize: 1Gi
    fileStore:
      enabled: true
      dir: /data
      pvc:
        enabled: true
        size: 5Gi
        storageClassName: longhorn-wdblack

podTemplate:
  merge:
    spec:
      tolerations:
        - key: "opi"
          operator: "Equal"
          value: "ok"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: nats-group
                    operator: In
                    values:
                      - core-ha
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - nats
                topologyKey: "kubernetes.io/hostname"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: nats

container:
  env:
    GOMEMLIMIT: 300MiB
  merge:
    resources:
      requests:
        cpu: "100m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"
