apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arcpat
  namespace: arc-runners
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: arc-runner-auth
    creationPolicy: Owner
  data:
    - secretKey: github_token
      remoteRef:
        key: "29760d6e-5359-4483-8277-b3ec016c700c"
