apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arcpat
  namespace: renovate
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: renovate-gh-pat
    creationPolicy: Owner
  data:
    - secretKey: RENOVATE_TOKEN
      remoteRef:
        key: "0d7602d8-5d15-461c-866b-b44a0135cab1"
