apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-telegram
  namespace: monitoring
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: alertmanager-telegram
    creationPolicy: Owner
  data:
    - secretKey: telegram-token
      remoteRef:
        key: "87ecec1b-e5a7-4ddd-8c4b-b41f00068d39"
