apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-admin
  namespace: nextcloud
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: nextcloud-admin
    creationPolicy: Owner
    template:
      data:
        nextcloud-username: "elia"
        nextcloud-password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "98925f4d-408e-4483-a50c-b4730147751f"
        property: "password"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-db
  namespace: nextcloud
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: nextcloud-db
    creationPolicy: Owner
    template:
      data:
        db-username: "nextcloud"
        db-password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "98925f4d-408e-4483-a50c-b4730147751f"
