apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster
spec:
  instances: 3
  affinity:
    tolerations:
      - key: "opi"
        operator: "Exists"
        effect: "NoSchedule"

  postgresql:
    parameters:
      max_slot_wal_keep_size: "1GB"
      wal_keep_size: "0"
      wal_compression: "on"
      autovacuum_vacuum_scale_factor: "0.01"
      autovacuum_analyze_scale_factor: "0.005"
      autovacuum_vacuum_cost_delay: "2ms"

  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: "kubernetes.io/hostname"
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          cnpg.io/cluster: pg-cluster


  managed:
    roles:
      - name: risingwave
        ensure: present
        comment: role used for risingwave
        login: true
        superuser: false
        connectionLimit: -1
        inherit: true
        passwordSecret:
          name: rw-metastore-secret
      - name: vikunja
        ensure: present
        comment: role used for vikunja
        login: true
        superuser: false
        connectionLimit: -1
        inherit: true
        passwordSecret:
          name: vikunja
      - name: lakekeeper
        ensure: present
        comment: role used for lakekeeper
        login: true
        superuser: false
        connectionLimit: -1
        inherit: true
        passwordSecret:
          name: lakekeeper-secret

  storage:
    size: 10Gi
    storageClass: longhorn-wdblack
  walStorage:
    size: 2Gi
    storageClass: longhorn-wdblack
  resources:
    limits:
      cpu: "1"
      memory: 1000Mi
    requests:
      cpu: 100m
      memory: 200Mi
