apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vikunja
  namespace: cnpg-system
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: vikunja
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "vikunja" 
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "1d29191d-f9b9-46d2-8f66-b3ec013c1f08"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vikunja
  namespace: vikunja
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: vikunja
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "vikunja" 
        password: "{{ .password }}"
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: "1d29191d-f9b9-46d2-8f66-b3ec013c1f08"
