apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lakekeeper-secret
  namespace: cnpg-system
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: lakekeeper-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "lakekeeper" 
        password: "{{ .pg }}"
  data:
    - secretKey: pg
      remoteRef:
        key: "fc2a2c29-829d-4b72-acc9-b416016fa559"
