apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-db
  namespace: cnpg-system
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: nextcloud-db
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "nextcloud"
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: "98925f4d-408e-4483-a50c-b4730147751f"
