apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-oauth-external
  namespace: tailscale
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: operator-oauth
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: "534c5bcb-93a0-4e15-adaf-b3e50186ebe7"
    - secretKey: client_secret
      remoteRef:
        key: "920a6cab-f271-419c-9a79-b3e501871054"
