apiVersion: v1
kind: ConfigMap
metadata:
  name: garage-config
data:
  garage.toml: |
    metadata_dir = "/data/meta"
    data_dir = "/data/objects"
    db_engine = "lmdb"
    replication_factor = 1

    rpc_bind_addr = "[::]:3901"
    # rpc_secret is injected via GARAGE_RPC_SECRET env var

    [db_options]
    fsync = false


    [s3_api]
    s3_region = "eu-lambronx-1"
    api_bind_addr = "[::]:3900"

    [admin]
    api_bind_addr = "[::]:3903"
