# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.3/deployment.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: garage
  labels:
    app: garage
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: garage
  template:
    metadata:
      labels:
        app: garage
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - elcungem
                      - elcunhp1
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - image: dxflrs/garage:v2.3.0
          name: garage
          command: ["/garage"]
          args:
            - "-c"
            - "/etc/garage/garage.toml"
            - "server"
            - "--single-node"
            - "--default-bucket"
          ports:
            - containerPort: 3900
              name: s3-api
            - containerPort: 3903
              name: admin
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "1"
          readinessProbe:
            tcpSocket:
              port: 3900
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3900
            initialDelaySeconds: 30
            periodSeconds: 20
          env:
            - name: GARAGE_RPC_SECRET
              valueFrom:
                secretKeyRef:
                  name: garage-secret
                  key: rpc_secret
            - name: GARAGE_DEFAULT_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: garage-secret
                  key: secret_id
            - name: GARAGE_DEFAULT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: garage-secret
                  key: secret_key
            - name: GARAGE_DEFAULT_BUCKET
              value: "hummock001"
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /etc/garage
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: garage-pvc
        - name: config
          configMap:
            name: garage-config
