apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: garage-secret
  data:
    - secretKey: rpc_secret
      remoteRef:
        key: "db33c013-94b8-4fa3-8ea8-b43501378f55"
    - secretKey: secret_id
      remoteRef:
        key: "05c2c173-3de5-4727-80a5-b416016a3c73"
    - secretKey: secret_key
      remoteRef:
        key: "01c16d85-1a29-4581-b417-b416016a58fa"
