apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc-runners
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/cunialino/homelab.git
      path: base/arc
    - chart: gha-runner-scale-set-controller
      repoURL: ghcr.io/actions/actions-runner-controller-charts
      targetRevision: 0.13.1
      helm:
        values: |
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
    - chart: gha-runner-scale-set
      repoURL: ghcr.io/actions/actions-runner-controller-charts
      targetRevision: 0.13.1
      helm:
        values: |
          githubConfigUrl: "https://github.com/cunialino/homelab"
          githubConfigSecret: arc-runner-auth
          runnerScaleSetName: "homelab-runner"
          containerMode:
            type: "kubernetes-novolume"
          listenerTemplate:
            spec:
              containers:
                - name: listener
                  resources:
                    requests:
                      cpu: "100m"
                      memory: "128Mi"
                    limits:
                      cpu: "200m"
                      memory: "256Mi"

          template:
            spec:
              containers:
                - name: runner
                  image: ghcr.io/actions/actions-runner:latest
                  command: ["/home/runner/run.sh"]
                  resources:
                    requests:
                      cpu: "100m"
                      memory: "128Mi"
                    limits:
                      cpu: "1000m"
                      memory: "256Mi"
              securityContext:
                fsGroup: 1001
          controllerServiceAccount:
            name: arc-runners-gha-rs-controller
            namespace: arc-runners
  destination:
    server: https://kubernetes.default.svc
    namespace: arc-runners
  syncPolicy:
    automated:
      enabled: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
