apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://argoproj.github.io/argo-helm'
      chart: argo-cd
      targetRevision: 9.5.15
      helm:
        valueFiles:
          - $my-repo/base/argocd/values.yaml
    - repoURL: 'https://github.com/cunialino/homelab.git'
      targetRevision: main
      ref: my-repo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
      prune: false
