apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-stack
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://cloudnative-pg.github.io/charts
      chart: cloudnative-pg
      targetRevision: 0.26.0
      helm:
        values: |
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi

    - repoURL: https://github.com/cunialino/homelab.git
      path: base/cnpg
      targetRevision: main
  
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  
  syncPolicy:
    automated:
      enabled: false
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
