apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crypto-lakehouse
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/cunialino/crypto-lakehouse.git'
    path: deploy/apps
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
      prune: true
