apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://kedacore.github.io/charts
      chart: keda
      targetRevision: 2.20.2
      helm:
        releaseName: keda
        valueFiles:
          - $my-repo/base/keda/values.yaml

    - repoURL: https://kedacore.github.io/charts
      chart: keda-add-ons-http
      targetRevision: 0.15.0
      helm:
        releaseName: keda-add-ons-http
        valueFiles:
          - $my-repo/base/keda/http-values.yaml

    - repoURL: https://github.com/cunialino/homelab.git
      path: base/keda
      targetRevision: main
      ref: my-repo

  destination:
    server: https://kubernetes.default.svc
    namespace: keda

  syncPolicy:
    automated:
      enabled: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true