apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 81.5.0
      helm:
        releaseName: prometheus
        valueFiles: 
          - $my-repo/base/monitoring/values.yaml

    - repoURL: https://github.com/cunialino/homelab.git
      path: base/monitoring
      targetRevision: main
      ref: my-repo
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  
  syncPolicy:
    automated:
      enabled: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
