apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rustfs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/cunialino/homelab.git'
    path: base/rustfs
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: rustfs
  syncPolicy:
    automated:
      enabled: false
      selfHeal: true
      prune: true
