apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seaweedfs-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/cunialino/homelab.git
    path: base/seaweedfs
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: seaweedfs
  syncPolicy:
    automated:
      enabled: false
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
