apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vikunja
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/cunialino/homelab.git'
    path: base/vikunja
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: vikunja
  syncPolicy:
    automated:
      enabled: false
      selfHeal: true
      prune: false
