apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
  namespace: external-secrets
spec:
  provider:
    bitwardensecretsmanager:
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      identityURL: "https://vault.bitwarden.eu./identity"
      apiURL: "https://vault.bitwarden.eu./api"
      organizationID: "f87c7181-4ada-49fe-890e-b3e00186b313"
      projectID: "d0bab4c6-25b3-444b-817e-b3e10007b25d"
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        namespace: external-secrets
        key: ca.crt
        
      auth:
        secretRef:
          credentials:
            name: bitwarden-access-token
            namespace: external-secrets
            key: token
