apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: external-secrets
  namespace: external-secrets
specs:
  - endpointSelector:
      matchLabels:
        app.kubernetes.io/name: external-secrets
        app.kubernetes.io/instance: external-secrets
    egress:
      - toEntities:
          - kube-apiserver
      - toEndpoints:
          - matchLabels:
              k8s-app: kube-dns
              io.kubernetes.pod.namespace: kube-system
        toPorts:
          - ports:
              - port: "53"
                protocol: UDP
              - port: "53"
                protocol: TCP
            rules:
              dns:
                - matchPattern: "*"
      - toEndpoints:
          - matchLabels:
              app.kubernetes.io/name: bitwarden-sdk-server
        toPorts:
          - ports:
              - port: "9998"
                protocol: TCP
      - toServices:
          - k8sService:
              serviceName: bitwarden-sdk-server
              namespace: external-secrets
        toPorts:
          - ports:
              - port: "9998"
                protocol: TCP
  - endpointSelector:
      matchLabels:
        app.kubernetes.io/name: bitwarden-sdk-server
    ingress:
      - fromEntities:
          - host
        toPorts:
          - ports:
              - port: "9998"
                protocol: TCP
      - fromEndpoints:
          - matchLabels:
              app.kubernetes.io/name: external-secrets
              app.kubernetes.io/instance: external-secrets
              io.kubernetes.pod.namespace: external-secrets
        toPorts:
          - ports:
              - port: "9998"
                protocol: TCP
    egress:
      - toEndpoints:
          - matchLabels:
              k8s-app: kube-dns
              io.kubernetes.pod.namespace: kube-system
        toPorts:
          - ports:
              - port: "53"
                protocol: UDP
              - port: "53"
                protocol: TCP
            rules:
              dns:
                - matchPattern: "*"
      - toFQDNs:
          - matchName: "vault.bitwarden.eu"
        toPorts:
          - ports:
              - port: "443"
                protocol: TCP
  - endpointSelector:
      matchLabels:
        app.kubernetes.io/name: external-secrets-webhook
    ingress:
      - fromEntities:
          - kube-apiserver
        toPorts:
          - ports:
              - port: "10250"
                protocol: TCP
      - fromEntities:
          - host
        toPorts:
          - ports:
              - port: "8081"
                protocol: TCP
    egress:
      - toEntities:
          - kube-apiserver
      - toEndpoints:
          - matchLabels:
              k8s-app: kube-dns
              io.kubernetes.pod.namespace: kube-system
        toPorts:
          - ports:
              - port: "53"
                protocol: UDP
              - port: "53"
                protocol: TCP
            rules:
              dns:
                - matchPattern: "*"
  - endpointSelector:
      matchLabels:
        app.kubernetes.io/name: external-secrets-cert-controller
    ingress:
      - fromEntities:
          - host
        toPorts:
          - ports:
              - port: "8081"
                protocol: TCP
    egress:
      - toEntities:
          - kube-apiserver
      - toEndpoints:
          - matchLabels:
              k8s-app: kube-dns
              io.kubernetes.pod.namespace: kube-system
        toPorts:
          - ports:
              - port: "53"
                protocol: UDP
              - port: "53"
                protocol: TCP
            rules:
              dns:
                - matchPattern: "*"
